### ISSUE TITLE
ValueError: Cannot load /home/tom/.cache/huggingface/hub/models

### ISSUE THREAD

**Issue by tom2698** [another-ai/stable_cascade_easy#6]
ValueError: Cannot load /home/tom/.cache/huggingface/hub/models--stabilityai--stable-cascade/snapshots/f2a84281d6f8db3c757195dd0c9a38dbdea90bb4/decoder because embedding.1.weight expected shape tensor(..., device='meta', size=(320, 64, 1, 1)), but got torch.Size([320, 16, 1, 1]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example

I get this error after running app.py and after it automatically downloads all the models. I've gone in and deleted the models from the cache and let it redownload but the same issue is happening. I'm running on Fedora Linux with a 4060Ti 16GB as well.

**Comment by ssnodgra** [comment]
I'm getting this same error on Windows 10 using an RTX 3060 (12GB).  It looks like it's very close to working until it blows up with this error.

ValueError: Cannot load C:\Users\xxxxxx\.cache\huggingface\hub\models--stabilityai--stable-cascade\snapshots\f2a84281d6f8db3c757195dd0c9a38dbdea90bb4\decoder because embedding.1.weight expected shape tensor(..., device='meta', size=(320, 64, 1, 1)), but got torch.Size([320, 16, 1, 1]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.
